"""Static phantom one-pager: show the product before they pay."""

from __future__ import annotations

import html
import re
from pathlib import Path
from typing import Any

_SLUG = re.compile(r"[^a-z0-9]+")


def slug(text: str, *, max_len: int = 40) -> str:
    s = _SLUG.sub("-", (text or "").lower()).strip("-")
    return (s[:max_len] or "lead").strip("-")


def _faqs(vertical: dict[str, Any], name: str) -> list[tuple[str, str]]:
    vid = str(vertical.get("id") or "")
    n = name or "us"
    catalog = {
        "salon": [
            ("Do you take walk-ins?", f"{n} can answer this 24/7 — sample only."),
            ("How do I book a color?", "Tap Book. The bot holds a chair. Sample only."),
            ("What if I need to cancel?", "Text the bot. It frees the slot. Sample only."),
        ],
        "estate": [
            ("Can I view this weekend?", "Bot qualifies budget + area. Sample only."),
            ("Are you the listing agent?", "Captures name + WhatsApp. Sample only."),
            ("What's the HOA?", "FAQ from your listings. Sample only."),
        ],
        "trucking": [
            ("Can you haul this week?", "Quote form + after-hours capture. Sample only."),
            ("Do you run reefer?", "FAQ from your lanes. Sample only."),
            ("MC / DOT?", "On the site, not buried in a PDF. Sample only."),
        ],
    }
    return catalog.get(
        vid,
        [
            ("Are you open now?", f"The {n} bot answers after hours. Sample only."),
            ("How do I book?", "One tap. Sample only."),
            ("What do you charge?", "Packages on the page. Sample only."),
        ],
    )


def render_phantom_html(
    lead: dict[str, Any],
    *,
    vertical: dict[str, Any],
    region: dict[str, Any],
) -> str:
    name = html.escape(str(lead.get("name") or "Your Business"))
    city = html.escape(str(lead.get("city") or lead.get("address") or ""))
    offer = html.escape(str(vertical.get("offer") or "AI website + chatbot"))
    pain = html.escape(str(vertical.get("pain") or "missed leads"))
    phone = html.escape(str(lead.get("phone") or ""))
    channel = str(region.get("primary_channel") or "email")
    cta = "WhatsApp us" if channel == "whatsapp" else "Book a 12-min demo"
    faqs = _faqs(vertical, str(lead.get("name") or "the shop"))
    faq_html = "".join(
        f"<div class='faq'><h3>{html.escape(q)}</h3><p>{html.escape(a)}</p></div>"
        for q, a in faqs
    )
    phone_line = f"<p class='phone'>{phone}</p>" if phone else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{name} — demo site (SAMPLE)</title>
  <style>
    :root {{ --bg:#0f1419; --card:#1a222c; --ink:#f4f1ea; --muted:#b7b1a4; --acc:#e8c547; }}
    * {{ box-sizing:border-box; }}
    body {{ margin:0; font-family:ui-sans-serif,system-ui,sans-serif; background:var(--bg); color:var(--ink); }}
    header {{ padding:2.2rem 1.4rem 1.2rem; max-width:720px; margin:auto; }}
    .banner {{ background:#5c3d2e; color:#f4e8d8; font-size:.8rem; letter-spacing:.04em; text-align:center; padding:.45rem; }}
    h1 {{ font-size:1.9rem; margin:.3rem 0; }}
    .sub {{ color:var(--muted); }}
    .card {{ background:var(--card); border-radius:16px; padding:1.2rem 1.3rem; margin:0 1.2rem 1rem; max-width:720px; margin-left:auto; margin-right:auto; }}
    .faq h3 {{ margin:.2rem 0; font-size:1rem; }}
    .faq p {{ margin:.2rem 0 .8rem; color:var(--muted); }}
    a.cta {{ display:block; text-align:center; background:var(--acc); color:#1a1408; font-weight:700; text-decoration:none; padding:.9rem 1rem; border-radius:12px; margin:1.2rem auto 2rem; max-width:720px; width:calc(100% - 2.4rem); }}
    footer {{ color:var(--muted); font-size:.75rem; text-align:center; padding:0 1rem 2rem; }}
  </style>
</head>
<body>
  <div class="banner">SAMPLE DEMO — not their live site. Built to show {name} what an AI site + bot looks like.</div>
  <header>
    <p class="sub">{city}</p>
    <h1>{name}</h1>
    <p>We stop {pain}. {offer}.</p>
    {phone_line}
  </header>
  <div class="card">
    <p><strong>Chatbot (sample FAQs)</strong></p>
    {faq_html}
  </div>
  <a class="cta" href="#">{cta}</a>
  <footer>Generated by the agency lead-gen hunter. Not affiliated with {name}. Sample copy only.</footer>
</body>
</html>
"""


def write_phantom(
    lead: dict[str, Any],
    dest_dir: Path,
    *,
    vertical: dict[str, Any],
    region: dict[str, Any],
) -> Path:
    dest_dir.mkdir(parents=True, exist_ok=True)
    path = dest_dir / "index.html"
    path.write_text(render_phantom_html(lead, vertical=vertical, region=region), encoding="utf-8")
    return path
