from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field

class PerformanceRecord(BaseModel):
    """Data Transfer Object for platform performance stats."""
    platform: str = Field(description="The platform name (e.g., youtube, wordpress, spotify)")
    platform_content_id: str = Field(description="The platform-specific ID for the content (e.g., video ID)")
    job_id: Optional[int] = Field(default=None, description="The internal Job ID if known")
    
    views: int = Field(default=0, description="Total views, listens, or reads")
    engagement_metrics: dict[str, Any] = Field(
        default_factory=dict, 
        description="Platform-specific engagement data (likes, comments, watch_time_seconds, etc.)"
    )
    revenue_cents: int = Field(default=0, description="Revenue generated by this content in cents")
    
    collected_at: datetime = Field(default_factory=datetime.utcnow, description="When these stats were collected")
