"""WhatsApp webhook handler — Twilio inbound → same Claude proxy → Twilio reply.

This is for client's CUSTOMERS talking to the bot (inbound only).
NOT connected to the leadgen cold-outreach pipeline in any way.

Constraints (hard — do not modify):
  - No outbound messages except in direct reply to an inbound message.
  - No proactive / broadcast messages of any kind.
  - No marketing DMs to leads (violates AGENCY_MASTER + WhatsApp policy).
  - LEAD_CAPTURED token detection works identically to the web chatbot.

Deployment modes:
  - Sandbox: set TWILIO_WHATSAPP_SANDBOX=true in .env — uses the
    Twilio sandbox number. No Meta verification needed for testing.
  - Production: Meta-verified WhatsApp Business number. Requires
    TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_WHATSAPP_NUMBER in .env.

Environment variables required:
    TWILIO_ACCOUNT_SID      — Twilio account SID
    TWILIO_AUTH_TOKEN       — Twilio auth token
    TWILIO_WHATSAPP_NUMBER  — your Twilio WhatsApp number (e.g. whatsapp:+14155238886)
    TWILIO_WHATSAPP_SANDBOX — set to "true" for sandbox mode (no Meta verification needed)
    DEMO_PROXY_URL          — optional, defaults to http://127.0.0.1:8787/v1/messages
"""

from __future__ import annotations

import csv
import json
import logging
import os
from pathlib import Path
from urllib import error as url_error
from urllib import parse as url_parse
from urllib import request as url_request

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parents[3]

# ── Paths ─────────────────────────────────────────────────────────────────
WA_NUMBERS_CONFIG = ROOT / "config" / "whatsapp_numbers.yaml"
CLIENTS_DIR       = ROOT / "clients"
LIVE_CSV          = ROOT / "output" / "leadgen_live" / "leads_LIVE.csv"

# ── Env vars ───────────────────────────────────────────────────────────────
_TWILIO_SID    = (os.getenv("TWILIO_ACCOUNT_SID")     or "").strip()
_TWILIO_TOKEN  = (os.getenv("TWILIO_AUTH_TOKEN")       or "").strip()
_WA_NUMBER     = (os.getenv("TWILIO_WHATSAPP_NUMBER")  or "").strip()
_SANDBOX       = (os.getenv("TWILIO_WHATSAPP_SANDBOX") or "").strip().lower() == "true"
_PROXY_URL     = (os.getenv("DEMO_PROXY_URL") or "http://127.0.0.1:8787/v1/messages").strip()

# In-memory conversation history per phone number (resets on process restart)
_SESSIONS: dict[str, list[dict[str, str]]] = {}

# LEAD_CAPTURED log file
_LEAD_LOG = ROOT / "output" / "leadgen_live" / "whatsapp_leads.csv"
_LEAD_LOG_COLS = ["timestamp", "from_number", "client_slug", "preview"]


def _load_number_map() -> dict[str, str]:
    """Load phone-number → client-slug mapping from config/whatsapp_numbers.yaml.
    Falls back to an empty dict if the file does not exist yet.
    """
    if not WA_NUMBERS_CONFIG.is_file():
        logger.warning("whatsapp_numbers.yaml not found — using empty number map")
        return {}
    try:
        import yaml  # type: ignore[import]
        with WA_NUMBERS_CONFIG.open(encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if not isinstance(data, dict):
            return {}
        numbers: dict[str, str] = {}
        for slug, cfg in data.items():
            if isinstance(cfg, dict):
                for num in (cfg.get("numbers") or []):
                    numbers[str(num).strip()] = str(slug)
            elif isinstance(cfg, str):
                numbers[str(cfg).strip()] = str(slug)
        return numbers
    except Exception as exc:  # noqa: BLE001
        logger.error("Failed to load whatsapp_numbers.yaml: %s", exc)
        return {}


def _load_client_config(slug: str) -> dict | None:
    """Load clients/<slug>/config.json generated by the onboarding CLI."""
    config_path = CLIENTS_DIR / slug / "config.json"
    if not config_path.is_file():
        logger.warning("Client config not found: %s", config_path)
        return None
    try:
        return json.loads(config_path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        logger.error("Failed to load client config %s: %s", config_path, exc)
        return None


def _build_system_prompt(client_cfg: dict) -> str:
    """Build system prompt identical in structure to client-chatbot-demo.html's buildSystemPrompt()."""
    services = client_cfg.get("services") or []
    hours    = client_cfg.get("hours") or {}
    faqs     = client_cfg.get("extraFaqs") or []
    name     = client_cfg.get("businessName", "this business")
    location = client_cfg.get("location", "")
    phone    = client_cfg.get("phone", "")
    booking  = client_cfg.get("bookingPolicy", "")

    svc_lines   = "\n".join(f"- {s['name']}: {s.get('price','')} ({s.get('duration','')})" for s in services)
    hours_lines = "\n".join(f"- {d}: {h}" for d, h in hours.items())
    faq_lines   = "\n".join(f"- {f}" for f in faqs)

    return (
        f"You are the friendly front-desk assistant for {name}, answering questions and helping "
        f"clients book appointments via WhatsApp. Speak like a warm, efficient receptionist — not a "
        f"corporate bot. Keep replies short (2-4 sentences max) since this is a chat interface.\n\n"
        f"BUSINESS INFO (use only this — never invent details):\n"
        f"Services and pricing:\n{svc_lines}\n\n"
        f"Hours:\n{hours_lines}\n\n"
        f"Location: {location}\nPhone: {phone}\nBooking policy: {booking}\n\n"
        f"Additional info:\n{faq_lines}\n\n"
        f"RULES:\n"
        f"- If asked to book: collect their name, desired service, and preferred date/time. "
        f"Confirm it back clearly, and tell them {name} will confirm shortly "
        f"(say this exact phrase: 'LEAD_CAPTURED' at the very end of your reply, on its own, "
        f"so the system can log it — the user will never see that token).\n"
        f"- If asked something you don't have info on, say you'll have the team follow up directly.\n"
        f"- Never invent prices, availability, or policies not listed above.\n"
        f"- Keep tone warm and human, never robotic."
    )


def _call_proxy(system: str, history: list[dict[str, str]]) -> str:
    """Forward to the local proxy — same endpoint as the web chatbots."""
    payload = {
        "model": "claude-sonnet-4-6",
        "max_tokens": 300,
        "system": system,
        "messages": history,
    }
    req = url_request.Request(
        _PROXY_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with url_request.urlopen(req, timeout=45) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    texts = [b["text"] for b in (data.get("content") or []) if b.get("type") == "text"]
    return "\n".join(texts).strip()


def _log_lead_capture(from_number: str, slug: str, preview: str) -> None:
    """Append a row to the WhatsApp lead-capture log — same tracker as web leads."""
    from datetime import datetime, timezone
    _LEAD_LOG.parent.mkdir(parents=True, exist_ok=True)
    exists = _LEAD_LOG.is_file()
    with _LEAD_LOG.open("a", newline="", encoding="utf-8") as f:
        import csv as _csv
        w = _csv.DictWriter(f, fieldnames=_LEAD_LOG_COLS, extrasaction="ignore")
        if not exists:
            w.writeheader()
        w.writerow({
            "timestamp":   datetime.now(timezone.utc).isoformat(),
            "from_number": from_number,
            "client_slug": slug,
            "preview":     preview[:80],
        })
    logger.info("WhatsApp lead captured: %s for client %s", from_number, slug)


def _send_twilio_reply(to: str, body: str) -> None:
    """Send a WhatsApp reply via Twilio REST API.
    Only called in direct reply to an inbound message — never proactively.
    """
    if not _TWILIO_SID or not _TWILIO_TOKEN or not _WA_NUMBER:
        raise RuntimeError(
            "Twilio credentials not configured. Set TWILIO_ACCOUNT_SID, "
            "TWILIO_AUTH_TOKEN, TWILIO_WHATSAPP_NUMBER in .env"
        )
    url = f"https://api.twilio.com/2010-04-01/Accounts/{_TWILIO_SID}/Messages.json"
    from_number = f"whatsapp:{_WA_NUMBER}" if not _WA_NUMBER.startswith("whatsapp:") else _WA_NUMBER
    data = url_parse.urlencode({
        "From": from_number,
        "To":   to if to.startswith("whatsapp:") else f"whatsapp:{to}",
        "Body": body,
    }).encode("utf-8")
    import base64
    token = base64.b64encode(f"{_TWILIO_SID}:{_TWILIO_TOKEN}".encode()).decode()
    req = url_request.Request(
        url,
        data=data,
        headers={
            "Authorization": f"Basic {token}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
        method="POST",
    )
    with url_request.urlopen(req, timeout=20) as resp:
        result = json.loads(resp.read().decode("utf-8"))
    logger.info("Twilio sent message SID=%s to=%s", result.get("sid"), to)


def handle_inbound(from_number: str, body: str) -> str:
    """Core handler: inbound WhatsApp message → LLM reply.

    Args:
        from_number: Sender's WhatsApp number (e.g. 'whatsapp:+15551234567')
        body: The raw message text

    Returns:
        The reply text (also sent via Twilio if credentials are configured).
    """
    number_map = _load_number_map()
    clean_num  = from_number.replace("whatsapp:", "").strip()
    slug       = None

    # Look up which client this number maps to
    for pattern, client_slug in number_map.items():
        if pattern in from_number or from_number.endswith(pattern.lstrip("+")):
            slug = client_slug
            break

    if slug is None:
        logger.warning("Unrecognized number %s — sending generic fallback", from_number)
        reply = (
            "Hi! Thanks for reaching out. We'll get back to you shortly. "
            "If this is urgent please call us directly."
        )
        try:
            _send_twilio_reply(from_number, reply)
        except Exception as exc:  # noqa: BLE001
            logger.error("Twilio send failed for unknown number: %s", exc)
        return reply

    client_cfg = _load_client_config(slug)
    if client_cfg is None:
        logger.error("No config for client slug %s", slug)
        reply = "Hi! I'm not quite set up yet — please call us directly. We'll sort this shortly."
        try:
            _send_twilio_reply(from_number, reply)
        except Exception as exc:  # noqa: BLE001
            logger.error("Twilio send failed: %s", exc)
        return reply

    system = _build_system_prompt(client_cfg)
    session_key = f"{slug}::{clean_num}"
    if session_key not in _SESSIONS:
        _SESSIONS[session_key] = []
    _SESSIONS[session_key].append({"role": "user", "content": body})

    try:
        raw_reply = _call_proxy(system, _SESSIONS[session_key])
    except Exception as exc:  # noqa: BLE001
        logger.error("Proxy call failed: %s", exc)
        raw_reply = "Sorry, I'm having a technical issue right now. Please call us directly."

    lead_captured = False
    if "LEAD_CAPTURED" in raw_reply:
        lead_captured = True
        raw_reply = raw_reply.replace("LEAD_CAPTURED", "").strip()
        _log_lead_capture(from_number, slug, body[:80])

    _SESSIONS[session_key].append({"role": "assistant", "content": raw_reply})

    try:
        _send_twilio_reply(from_number, raw_reply)
    except Exception as exc:  # noqa: BLE001
        logger.error("Twilio send failed: %s", exc)

    if lead_captured:
        logger.info("LEAD_CAPTURED for client=%s from=%s", slug, from_number)

    return raw_reply


# ── Minimal Flask webhook (for Twilio webhook URL configuration) ───────────
# Run with: python -m src.channels.whatsapp.webhook
# Twilio webhook URL: http://<your-server>/whatsapp/inbound

def create_app():  # noqa: ANN201
    """Create a minimal Flask app for Twilio webhook."""
    try:
        from flask import Flask, Response, request
    except ImportError as exc:
        raise ImportError(
            "Flask is required for the WhatsApp webhook server. "
            "Install it: pip install flask"
        ) from exc

    app = Flask(__name__)

    @app.route("/health", methods=["GET"])
    def health():  # noqa: ANN202
        return Response(json.dumps({"ok": True, "mode": "sandbox" if _SANDBOX else "production"}),
                        content_type="application/json")

    @app.route("/whatsapp/inbound", methods=["POST"])
    def whatsapp_inbound():  # noqa: ANN202
        from_number = request.form.get("From", "")
        body        = (request.form.get("Body") or "").strip()
        if not from_number or not body:
            return Response("<Response/>", content_type="text/xml", status=200)
        try:
            handle_inbound(from_number=from_number, body=body)
        except Exception as exc:  # noqa: BLE001
            logger.error("handle_inbound failed: %s", exc)
        # Twilio expects an empty TwiML response (reply is sent via API, not this response)
        return Response("<Response/>", content_type="text/xml", status=200)

    return app


if __name__ == "__main__":
    import sys
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 5001
    mode = "SANDBOX" if _SANDBOX else "PRODUCTION"
    print(f"WhatsApp webhook server — mode={mode}  port={port}")
    print(f"Twilio webhook URL: http://YOUR_SERVER:{port}/whatsapp/inbound")
    create_app().run(host="0.0.0.0", port=port, debug=False)
